/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/usr/local/Cellar/nim/0.13.0/nim/lib -o /Users/molikto/Projects/Others/ExercisesAndCourses/PLHelloWords/nim/nimcache/fib.o /Users/molikto/Projects/Others/ExercisesAndCourses/PLHelloWords/nim/nimcache/fib.c */
#define NIM_INTBITS 64

#include "nimbase.h"
N_NIMCALL(int, fib)(int a);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, fibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, fibDatInit000)(void);

N_NIMCALL(int, fib)(int a) {
	int result;
	result = 0;
	{
		if (!(a <= ((NI32) 2))) goto LA3;
		result = ((int) 1);
	}
	goto LA1;
	LA3: ;
	{
		int LOC6;
		int LOC7;
		LOC6 = 0;
		LOC6 = fib((NI32)(a - ((NI32) 1)));
		LOC7 = 0;
		LOC7 = fib((NI32)(a - ((NI32) 2)));
		result = (NI32)(LOC6 + LOC7);
	}
	LA1: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	fibDatInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	fibInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

NIM_EXTERNC N_NOINLINE(void, fibInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, fibDatInit000)(void) {
}

