/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/usr/local/Cellar/nim/0.13.0/nim/lib -o /Users/molikto/Projects/Others/ExercisesAndCourses/PLHelloWords/nim/nimcache/fib.o /Users/molikto/Projects/Others/ExercisesAndCourses/PLHelloWords/nim/nimcache/fib.h */
#ifndef __fib__
#define __fib__
#define NIM_INTBITS 64

#include "nimbase.h"
N_NOCONV(void, signalHandler)(int sig);
N_NIMCALL(NI, getRefcount)(void* p);
N_NIMCALL(int, fib)(int a);
N_CDECL(void, NimMain)(void);
#endif /* __fib__ */
