/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/usr/local/Cellar/nim/0.13.0/nim/lib -o /Users/molikto/Projects/Others/ExercisesAndCourses/PLHelloWords/nim/nimcache/stdlib_system.o /Users/molikto/Projects/Others/ExercisesAndCourses/PLHelloWords/nim/nimcache/stdlib_system.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/mman.h>
#include <stdio.h>
#include <stdlib.h>
#include <setjmp.h>
#include <signal.h>
typedef struct Exception Exception;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Avlnode29886 Avlnode29886;
typedef struct Gcheap50018 Gcheap50018;
typedef struct Gcstack50016 Gcstack50016;
typedef struct Cellseq47721 Cellseq47721;
typedef struct Cell47705 Cell47705;
typedef struct Cellset47717 Cellset47717;
typedef struct Pagedesc47713 Pagedesc47713;
typedef struct Memregion29888 Memregion29888;
typedef struct Smallchunk29840 Smallchunk29840;
typedef struct Llchunk29882 Llchunk29882;
typedef struct Bigchunk29842 Bigchunk29842;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Gcstat50014 Gcstat50014;
typedef struct Basechunk29838 Basechunk29838;
typedef struct Freecell29830 Freecell29830;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TSafePoint TSafePoint;
typedef struct TNimObject TNimObject;
typedef N_NIMCALL_PTR(NIM_BOOL, TY10009) (Exception* e);
typedef N_NIMCALL_PTR(NIM_BOOL, TY10014) (Exception* e);
typedef N_NIMCALL_PTR(void, TY10019) (void);
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
typedef Avlnode29886* TY29893[2];
struct  Avlnode29886  {
TY29893 link;
NI key;
NI upperbound;
NI level;
};
struct  Cellseq47721  {
NI len;
NI cap;
Cell47705** d;
};
struct  Cellset47717  {
NI counter;
NI max;
Pagedesc47713* head;
Pagedesc47713** data;
};
typedef Smallchunk29840* TY29903[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {
Trunkbuckets29812 data;
};
struct  Memregion29888  {
NI minlargeobj;
NI maxlargeobj;
TY29903 freesmallchunks;
Llchunk29882* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29842* freechunkslist;
Intset29814 chunkstarts;
Avlnode29886* root;
Avlnode29886* deleted;
Avlnode29886* last;
Avlnode29886* freeavlnodes;
};
struct  Gcstat50014  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50018  {
Gcstack50016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47721 zct;
Cellseq47721 decstack;
Cellset47717 cycleroots;
Cellseq47721 tempstack;
NI recgclock;
Memregion29888 region;
Gcstat50014 stat;
};
struct  Basechunk29838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29840  {
  Basechunk29838 Sup;
Smallchunk29840* next;
Smallchunk29840* prev;
Freecell29830* freelist;
NI free;
NI acc;
NF data;
};
struct  Bigchunk29842  {
  Basechunk29838 Sup;
Bigchunk29842* next;
Bigchunk29842* prev;
NI align;
NF data;
};
typedef NI TY29819[8];
struct  Trunk29810  {
Trunk29810* next;
NI key;
TY29819 bits;
};
struct  Llchunk29882  {
NI size;
NI acc;
Llchunk29882* next;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Freecell29830  {
Freecell29830* next;
NI zerofield;
};
typedef N_NIMCALL_PTR(void, TY19401) (NimStringDesc* msg);
typedef TFrame* TY20003[128];
struct  Cell47705  {
NI refcount;
TNimType* typ;
};
struct  Pagedesc47713  {
Pagedesc47713* next;
NI key;
TY29819 bits;
};
typedef N_NIMCALL_PTR(void, Finalizer) (void* self);
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Gcstack50016  {
Gcstack50016* prev;
Gcstack50016* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY18011;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY18011 raiseAction;
};
static N_INLINE(void, initallocator_11601)(void);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NIMCALL(void, initgc_11401)(void);
N_NIMCALL(void, init_47803)(Cellseq47721* s, NI cap);
N_NOCONV(void*, alloc0_7417)(NI size);
N_NIMCALL(void*, alloc0_46416)(Memregion29888* allocator, NI size);
N_NIMCALL(void*, alloc_46240)(Memregion29888* allocator, NI size);
N_NIMCALL(void*, rawalloc_37068)(Memregion29888* a, NI requestedsize);
static N_INLINE(NI, roundup_28401)(NI x, NI v);
N_NIMCALL(Smallchunk29840*, getsmallchunk_36412)(Memregion29888* a);
N_NIMCALL(Bigchunk29842*, getbigchunk_35614)(Memregion29888* a, NI size);
static N_INLINE(void, listremove_33402)(Bigchunk29842** head, Bigchunk29842* c);
N_NIMCALL(void, splitchunk_35409)(Memregion29888* a, Bigchunk29842* c, NI size);
static N_INLINE(void, updateprevsize_32468)(Memregion29888* a, Bigchunk29842* c, NI prevsize);
static N_INLINE(NIM_BOOL, isaccessible_32415)(Memregion29888* a, void* p);
N_NIMCALL(NIM_BOOL, contains_31132)(Intset29814* s, NI key);
N_NIMCALL(Trunk29810*, intsetget_31083)(Intset29814* t, NI key);
static N_INLINE(NI, pageindex_31575)(void* p);
N_NIMCALL(void, incl_31153)(Memregion29888* a, Intset29814* s, NI key);
N_NIMCALL(Trunk29810*, intsetput_31105)(Memregion29888* a, Intset29814* t, NI key);
N_NIMCALL(void*, llalloc_30043)(Memregion29888* a, NI size);
static N_INLINE(void*, osallocpages_29615)(NI size);
N_NOINLINE(void, raiseoutofmem_28234)(void);
static N_INLINE(void, inccurrmem_30002)(Memregion29888* a, NI bytes);
static N_INLINE(NI, pageindex_31570)(Basechunk29838* c);
static N_INLINE(void, listadd_34623)(Bigchunk29842** head, Bigchunk29842* c);
N_NIMCALL(Bigchunk29842*, requestoschunks_31587)(Memregion29888* a, NI size);
static N_INLINE(void, listadd_38016)(Smallchunk29840** head, Smallchunk29840* c);
static N_INLINE(void, listremove_40802)(Smallchunk29840** head, Smallchunk29840* c);
N_NIMCALL(void, add_30953)(Memregion29888* a, Avlnode29886** t, NI key, NI upperbound);
N_NIMCALL(Avlnode29886*, allocavlnode_30227)(Memregion29888* a, NI key, NI upperbound);
N_NIMCALL(void, skew_30934)(Avlnode29886** t);
N_NIMCALL(void, split_30939)(Avlnode29886** t);
N_NIMCALL(void, init_47818)(Cellset47717* s);
N_NOCONV(void, signalHandler)(int sig);
N_NIMCALL(void, showerrormessage_19606)(NCSTRING data);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, toNimStr)(NCSTRING str, NI len);
N_NIMCALL(NimStringDesc*, rawNewStringNoInit)(NI space);
N_NIMCALL(void*, newObjNoInit)(TNimType* typ, NI size);
N_NIMCALL(void*, rawnewobj_57801)(TNimType* typ, NI size, Gcheap50018* gch);
N_NIMCALL(void, collectct_52007)(Gcheap50018* gch);
N_NOINLINE(NI, stacksize_71801)(void);
static N_INLINE(NI, getoccupiedmem_47630)(Memregion29888* a);
N_NIMCALL(void, collectctbody_75609)(Gcheap50018* gch);
static N_INLINE(void, prepareforinteriorpointerchecking_45088)(Memregion29888* a);
N_NIMCALL(NI, lowgauge_30812)(Avlnode29886* n);
N_NIMCALL(NI, highgauge_30829)(Avlnode29886* n);
N_CDECL(void, markstackandregisters_73037)(Gcheap50018* gch);
static N_INLINE(void, gcmark_70816)(Gcheap50018* gch, void* p);
static N_INLINE(Cell47705*, usrtocell_51640)(void* usr);
N_NIMCALL(void*, interiorallocatedptr_45092)(Memregion29888* a, void* p);
static N_INLINE(Basechunk29838*, pageaddr_31580)(void* p);
static N_INLINE(NIM_BOOL, chunkunused_31489)(Basechunk29838* c);
static N_INLINE(NIM_BOOL, issmallchunk_31469)(Basechunk29838* c);
N_NIMCALL(Avlnode29886*, inrange_30881)(Avlnode29886* root, NI key);
static N_INLINE(void, add_47783)(Cellseq47721* s, Cell47705* c);
N_NOCONV(void*, alloc_7401)(NI size);
N_NOCONV(void, dealloc_7448)(void* p);
N_NIMCALL(void, dealloc_46422)(Memregion29888* allocator, void* p);
N_NIMCALL(void, rawdealloc_43417)(Memregion29888* a, void* p);
N_NIMCALL(void, freebigchunk_32603)(Memregion29888* a, Bigchunk29842* c_32607);
N_NIMCALL(void, excl_31164)(Intset29814* s, NI key);
N_NIMCALL(void, freeoschunks_32207)(Memregion29888* a, void* p, NI size);
static N_INLINE(void, osdeallocpages_29621)(void* p, NI size);
static N_INLINE(void, deccurrmem_30016)(Memregion29888* a, NI bytes);
N_NIMCALL(void, del_31001)(Memregion29888* a, Avlnode29886** t, NI x);
static N_INLINE(void, deallocavlnode_30803)(Memregion29888* a, Avlnode29886* n);
N_NIMCALL(void, markthreadstacks_71403)(Gcheap50018* gch);
N_NIMCALL(NIM_BOOL, collectzct_70206)(Gcheap50018* gch);
static N_INLINE(NIM_BOOL, canbecycleroot_51658)(Cell47705* c);
N_NIMCALL(void, excl_48474)(Cellset47717* s, Cell47705* cell);
N_NIMCALL(Pagedesc47713*, cellsetget_47850)(Cellset47717* t, NI key);
static N_INLINE(NI, nexttry_47845)(NI h, NI maxhash);
N_NIMCALL(void, preparedealloc_52208)(Cell47705* cell);
static N_INLINE(void*, celltousr_51622)(Cell47705* cell);
N_NIMCALL(void, forallchildren_52014)(Cell47705* cell, NU8 op);
N_NIMCALL(void, forallchildrenaux_52022)(void* dest, TNimType* mt, NU8 op);
N_NIMCALL(void, dooperation_52018)(void* p, NU8 op);
static N_INLINE(void, decref_53601)(Cell47705* c);
static N_INLINE(void, rtladdzct_53201)(Cell47705* c);
N_NOINLINE(void, addzct_51617)(Cellseq47721* s, Cell47705* c);
static N_INLINE(void, rtladdcycleroot_52420)(Cell47705* c);
N_NOINLINE(void, incl_48447)(Cellset47717* s, Cell47705* cell);
N_NIMCALL(Pagedesc47713*, cellsetput_48241)(Cellset47717* t, NI key);
N_NIMCALL(void, cellsetenlarge_48203)(Cellset47717* t);
N_NIMCALL(void, cellsetrawinsert_47870)(Cellset47717* t, Pagedesc47713** data, Pagedesc47713* desc);
N_NIMCALL(void, markgray_67202)(Cell47705* s);
N_NIMCALL(void, scan_67601)(Cell47705* s);
N_NIMCALL(void, scanblack_67401)(Cell47705* s);
N_NIMCALL(void, collectwhite_67801)(Cell47705* s);
N_NIMCALL(NIM_BOOL, isallocatedptr_36802)(Memregion29888* a, void* p);
N_NIMCALL(void, freecycliccell_66415)(Gcheap50018* gch, Cell47705* c);
N_NIMCALL(void, forallslotsaux_56205)(void* dest, TNimNode* n, NU8 op);
N_NIMCALL(TNimNode*, selectbranch_27807)(void* aa, TNimNode* n);
N_NIMCALL(NI, getdiscriminant_27404)(void* aa, TNimNode* n);
N_NIMCALL(void, collectcycles_70420)(Gcheap50018* gch);
N_NIMCALL(void, markroots_68002)(Gcheap50018* gch);
N_NIMCALL(void, collectroots_70401)(Gcheap50018* gch);
N_NIMCALL(void, cellsetreset_56201)(Cellset47717* s);
N_NIMCALL(void, deinit_47826)(Cellset47717* s);
N_NIMCALL(NI, getoccupiedmem_8055)(void);
N_NIMCALL(NI, gettotalmem_8059)(void);
N_NIMCALL(NI, getfreemem_8057)(void);
N_NIMCALL(void, unmarkstackandregisters_75402)(Gcheap50018* gch);
static N_INLINE(void, addnewobjtozct_57274)(Cell47705* res, Gcheap50018* gch);
N_NIMCALL(void, writetostderr_19601)(NCSTRING msg);
N_NIMCALL(void, write_15701)(FILE* f, NCSTRING c);
N_NIMCALL(void, registersignalhandler_23202)(void);
N_NIMCALL(NI, getRefcount)(void* p);
STRING_LITERAL(TMP4, "out of memory", 13);
NIM_BOOL nimvm_5751;
NI nim_program_result;
TY10009 globalraisehook_10013;
TY10014 localraisehook_10018;
TY10019 outofmemhook_10021;
TNimType strdesc_12203;
TY19401 errormessagewriter_19404;
TFrame* frameptr_19636;
TSafePoint* exchandler_19637;
Exception* currexception_19639;
TY20003 tempframes_20004;
Avlnode29886 bottomdata_29919;
Avlnode29886* bottom_29920;
Gcheap50018 gch_50059;
NIM_BOOL localgcinitialized_71824;
NIM_CHAR decimalpoint_80805;

static N_INLINE(void, initallocator_11601)(void) {
	bottom_29920 = (&bottomdata_29919);
	(*bottom_29920).link[(((NI) 0))- 0] = bottom_29920;
	(*bottom_29920).link[(((NI) 1))- 0] = bottom_29920;
}

N_NOINLINE(void, setStackBottom)(void* thestackbottom) {
	{
		if (!(gch_50059.stackbottom == NIM_NIL)) goto LA3;
		gch_50059.stackbottom = thestackbottom;
	}
	goto LA1;
	LA3: ;
	{
		NI a;
		NI b;
		a = ((NI) (thestackbottom));
		b = ((NI) (gch_50059.stackbottom));
		gch_50059.stackbottom = ((void*) (((a >= b) ? a : b)));
	}
	LA1: ;
}

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) ((&locals)));
	setStackBottom(locals);
}

static N_INLINE(NI, roundup_28401)(NI x, NI v) {
	NI result;
	result = 0;
	result = (NI)((NI)(x + (NI)(v - ((NI) 1))) & (NI)((NU64) ~((NI)(v - ((NI) 1)))));
	return result;
}

static N_INLINE(void, listremove_33402)(Bigchunk29842** head, Bigchunk29842* c) {
	{
		if (!(c == (*head))) goto LA3;
		(*head) = (*c).next;
		{
			if (!!(((*head) == NIM_NIL))) goto LA7;
			(*(*head)).prev = NIM_NIL;
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		(*(*c).prev).next = (*c).next;
		{
			if (!!(((*c).next == NIM_NIL))) goto LA12;
			(*(*c).next).prev = (*c).prev;
		}
		LA12: ;
	}
	LA1: ;
	(*c).next = NIM_NIL;
	(*c).prev = NIM_NIL;
}

N_NIMCALL(Trunk29810*, intsetget_31083)(Intset29814* t, NI key) {
	Trunk29810* result;
	Trunk29810* it;
{	result = 0;
	it = (*t).data[((NI)(key & ((NI) 255)))- 0];
	{
		while (1) {
			if (!!((it == NIM_NIL))) goto LA2;
			{
				if (!((*it).key == key)) goto LA5;
				result = it;
				goto BeforeRet;
			}
			LA5: ;
			it = (*it).next;
		} LA2: ;
	}
	result = NIM_NIL;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, contains_31132)(Intset29814* s, NI key) {
	NIM_BOOL result;
	Trunk29810* t;
	result = 0;
	t = intsetget_31083(s, (NI)((NU64)(key) >> (NU64)(((NI) 9))));
	{
		NI u;
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)(key & ((NI) 511));
		result = !(((NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63))))))) == ((NI) 0)));
	}
	goto LA1;
	LA3: ;
	{
		result = NIM_FALSE;
	}
	LA1: ;
	return result;
}

static N_INLINE(NI, pageindex_31575)(void* p) {
	NI result;
	result = 0;
	result = (NI)((NU64)(((NI) (p))) >> (NU64)(((NI) 12)));
	return result;
}

static N_INLINE(NIM_BOOL, isaccessible_32415)(Memregion29888* a, void* p) {
	NIM_BOOL result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = pageindex_31575(p);
	result = contains_31132((&(*a).chunkstarts), LOC1);
	return result;
}

static N_INLINE(void, updateprevsize_32468)(Memregion29888* a, Bigchunk29842* c, NI prevsize) {
	Basechunk29838* ri;
	ri = ((Basechunk29838*) ((NI)((NU64)(((NI) (c))) + (NU64)((*c).Sup.size))));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isaccessible_32415((&(*a)), ((void*) (ri)));
		if (!LOC3) goto LA4;
		(*ri).prevsize = prevsize;
	}
	LA4: ;
}

N_NOINLINE(void, raiseoutofmem_28234)(void) {
	{
		if (!!((outofmemhook_10021 == NIM_NIL))) goto LA3;
		outofmemhook_10021();
	}
	LA3: ;
	printf("%s\012", ((NimStringDesc*) &TMP4)? (((NimStringDesc*) &TMP4))->data:"nil");
	fflush(stdout);
	exit(((NI) 1));
}

static N_INLINE(void*, osallocpages_29615)(NI size) {
	void* result;
	result = 0;
	result = mmap(NIM_NIL, size, ((int) 3), ((NI32) 4098), ((int) -1), ((NI) 0));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (result == NIM_NIL);
		if (LOC3) goto LA4;
		LOC3 = (result == ((void*) -1));
		LA4: ;
		if (!LOC3) goto LA5;
		raiseoutofmem_28234();
	}
	LA5: ;
	return result;
}

static N_INLINE(void, inccurrmem_30002)(Memregion29888* a, NI bytes) {
	(*a).currmem += bytes;
}

N_NIMCALL(void*, llalloc_30043)(Memregion29888* a, NI size) {
	void* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		Llchunk29882* old;
		void* LOC7;
		LOC3 = 0;
		LOC3 = ((*a).llmem == NIM_NIL);
		if (LOC3) goto LA4;
		LOC3 = ((*(*a).llmem).size < size);
		LA4: ;
		if (!LOC3) goto LA5;
		old = (*a).llmem;
		LOC7 = 0;
		LOC7 = osallocpages_29615(((NI) 4096));
		(*a).llmem = ((Llchunk29882*) (LOC7));
		inccurrmem_30002(a, ((NI) 4096));
		(*(*a).llmem).size = (NI)(((NI) 4096) - ((NI)sizeof(Llchunk29882)));
		(*(*a).llmem).acc = ((NI)sizeof(Llchunk29882));
		(*(*a).llmem).next = old;
	}
	LA5: ;
	result = ((void*) ((NI)(((NI) ((*a).llmem)) + (*(*a).llmem).acc)));
	(*(*a).llmem).size -= size;
	(*(*a).llmem).acc += size;
	zeroMem(result, ((NI) (size)));
	return result;
}

N_NIMCALL(Trunk29810*, intsetput_31105)(Memregion29888* a, Intset29814* t, NI key) {
	Trunk29810* result;
	result = 0;
	result = intsetget_31083((&(*t)), key);
	{
		void* LOC5;
		if (!(result == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = llalloc_30043(a, ((NI)sizeof(Trunk29810)));
		result = ((Trunk29810*) (LOC5));
		(*result).next = (*t).data[((NI)(key & ((NI) 255)))- 0];
		(*t).data[((NI)(key & ((NI) 255)))- 0] = result;
		(*result).key = key;
	}
	LA3: ;
	return result;
}

N_NIMCALL(void, incl_31153)(Memregion29888* a, Intset29814* s, NI key) {
	Trunk29810* t;
	NI u;
	t = intsetput_31105(a, s, (NI)((NU64)(key) >> (NU64)(((NI) 9))));
	u = (NI)(key & ((NI) 511));
	(*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63)))))));
}

static N_INLINE(NI, pageindex_31570)(Basechunk29838* c) {
	NI result;
	result = 0;
	result = (NI)((NU64)(((NI) (c))) >> (NU64)(((NI) 12)));
	return result;
}

static N_INLINE(void, listadd_34623)(Bigchunk29842** head, Bigchunk29842* c) {
	(*c).next = (*head);
	{
		if (!!(((*head) == NIM_NIL))) goto LA3;
		(*(*head)).prev = c;
	}
	LA3: ;
	(*head) = c;
}

N_NIMCALL(void, splitchunk_35409)(Memregion29888* a, Bigchunk29842* c, NI size) {
	Bigchunk29842* rest;
	Basechunk29838* LOC1;
	NI LOC2;
	rest = ((Bigchunk29842*) ((NI)((NU64)(((NI) (c))) + (NU64)(size))));
	(*rest).Sup.size = (NI)((*c).Sup.size - size);
	(*rest).Sup.used = NIM_FALSE;
	(*rest).next = NIM_NIL;
	(*rest).prev = NIM_NIL;
	(*rest).Sup.prevsize = size;
	updateprevsize_32468(a, c, (*rest).Sup.size);
	(*c).Sup.size = size;
	LOC1 = 0;
	LOC1 = &rest->Sup;
	LOC2 = 0;
	LOC2 = pageindex_31570(LOC1);
	incl_31153(a, (&(*a).chunkstarts), LOC2);
	listadd_34623(&(*a).freechunkslist, rest);
}

N_NIMCALL(Bigchunk29842*, requestoschunks_31587)(Memregion29888* a, NI size) {
	Bigchunk29842* result;
	void* LOC1;
	NI nxt;
	Basechunk29838* next;
	NI lastsize;
	NI prv;
	Basechunk29838* prev;
	result = 0;
	inccurrmem_30002(a, size);
	(*a).freemem += size;
	LOC1 = 0;
	LOC1 = osallocpages_29615(size);
	result = ((Bigchunk29842*) (LOC1));
	(*result).next = NIM_NIL;
	(*result).prev = NIM_NIL;
	(*result).Sup.used = NIM_FALSE;
	(*result).Sup.size = size;
	nxt = (NI)((NU64)(((NI) (result))) + (NU64)(size));
	next = ((Basechunk29838*) (nxt));
	{
		NI LOC4;
		NIM_BOOL LOC5;
		LOC4 = 0;
		LOC4 = pageindex_31570(next);
		LOC5 = 0;
		LOC5 = contains_31132((&(*a).chunkstarts), LOC4);
		if (!LOC5) goto LA6;
		(*next).prevsize = size;
	}
	LA6: ;
	{
		if (!!(((*a).lastsize == ((NI) 0)))) goto LA10;
		lastsize = (*a).lastsize;
	}
	goto LA8;
	LA10: ;
	{
		lastsize = ((NI) 4096);
	}
	LA8: ;
	prv = (NI)((NU64)(((NI) (result))) - (NU64)(lastsize));
	prev = ((Basechunk29838*) (prv));
	{
		NIM_BOOL LOC15;
		NI LOC16;
		LOC15 = 0;
		LOC16 = 0;
		LOC16 = pageindex_31570(prev);
		LOC15 = contains_31132((&(*a).chunkstarts), LOC16);
		if (!(LOC15)) goto LA17;
		LOC15 = ((*prev).size == lastsize);
		LA17: ;
		if (!LOC15) goto LA18;
		(*result).Sup.prevsize = lastsize;
	}
	goto LA13;
	LA18: ;
	{
		(*result).Sup.prevsize = ((NI) 0);
	}
	LA13: ;
	(*a).lastsize = size;
	return result;
}

N_NIMCALL(Bigchunk29842*, getbigchunk_35614)(Memregion29888* a, NI size) {
	Bigchunk29842* result;
	Basechunk29838* LOC16;
	NI LOC17;
	result = 0;
	result = (*a).freechunkslist;
	{
		{
			while (1) {
				if (!!((result == NIM_NIL))) goto LA3;
				{
					if (!((*result).Sup.size == size)) goto LA6;
					listremove_33402(&(*a).freechunkslist, result);
					goto LA1;
				}
				goto LA4;
				LA6: ;
				{
					if (!(size < (*result).Sup.size)) goto LA9;
					listremove_33402(&(*a).freechunkslist, result);
					splitchunk_35409(a, result, size);
					goto LA1;
				}
				goto LA4;
				LA9: ;
				LA4: ;
				result = (*result).next;
			} LA3: ;
		}
		{
			if (!(size < ((NI) 524288))) goto LA13;
			result = requestoschunks_31587(a, ((NI) 524288));
			splitchunk_35409(a, result, size);
		}
		goto LA11;
		LA13: ;
		{
			result = requestoschunks_31587(a, size);
		}
		LA11: ;
	} LA1: ;
	(*result).Sup.prevsize = ((NI) 0);
	(*result).Sup.used = NIM_TRUE;
	LOC16 = 0;
	LOC16 = &result->Sup;
	LOC17 = 0;
	LOC17 = pageindex_31570(LOC16);
	incl_31153(a, (&(*a).chunkstarts), LOC17);
	(*a).freemem -= size;
	return result;
}

N_NIMCALL(Smallchunk29840*, getsmallchunk_36412)(Memregion29888* a) {
	Smallchunk29840* result;
	Bigchunk29842* res;
	result = 0;
	res = getbigchunk_35614(a, ((NI) 4096));
	result = ((Smallchunk29840*) (res));
	return result;
}

static N_INLINE(void, listadd_38016)(Smallchunk29840** head, Smallchunk29840* c) {
	(*c).next = (*head);
	{
		if (!!(((*head) == NIM_NIL))) goto LA3;
		(*(*head)).prev = c;
	}
	LA3: ;
	(*head) = c;
}

static N_INLINE(void, listremove_40802)(Smallchunk29840** head, Smallchunk29840* c) {
	{
		if (!(c == (*head))) goto LA3;
		(*head) = (*c).next;
		{
			if (!!(((*head) == NIM_NIL))) goto LA7;
			(*(*head)).prev = NIM_NIL;
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		(*(*c).prev).next = (*c).next;
		{
			if (!!(((*c).next == NIM_NIL))) goto LA12;
			(*(*c).next).prev = (*c).prev;
		}
		LA12: ;
	}
	LA1: ;
	(*c).next = NIM_NIL;
	(*c).prev = NIM_NIL;
}

N_NIMCALL(Avlnode29886*, allocavlnode_30227)(Memregion29888* a, NI key, NI upperbound) {
	Avlnode29886* result;
	result = 0;
	{
		if (!!(((*a).freeavlnodes == NIM_NIL))) goto LA3;
		result = (*a).freeavlnodes;
		(*a).freeavlnodes = (*(*a).freeavlnodes).link[(((NI) 0))- 0];
	}
	goto LA1;
	LA3: ;
	{
		void* LOC6;
		LOC6 = 0;
		LOC6 = llalloc_30043(a, ((NI)sizeof(Avlnode29886)));
		result = ((Avlnode29886*) (LOC6));
	}
	LA1: ;
	(*result).key = key;
	(*result).upperbound = upperbound;
	(*result).link[(((NI) 0))- 0] = bottom_29920;
	(*result).link[(((NI) 1))- 0] = bottom_29920;
	(*result).level = ((NI) 1);
	return result;
}

N_NIMCALL(void, skew_30934)(Avlnode29886** t) {
	{
		Avlnode29886* temp;
		if (!((*(*(*t)).link[(((NI) 0))- 0]).level == (*(*t)).level)) goto LA3;
		temp = (*t);
		(*t) = (*(*t)).link[(((NI) 0))- 0];
		(*temp).link[(((NI) 0))- 0] = (*(*t)).link[(((NI) 1))- 0];
		(*(*t)).link[(((NI) 1))- 0] = temp;
	}
	LA3: ;
}

N_NIMCALL(void, split_30939)(Avlnode29886** t) {
	{
		Avlnode29886* temp;
		if (!((*(*(*(*t)).link[(((NI) 1))- 0]).link[(((NI) 1))- 0]).level == (*(*t)).level)) goto LA3;
		temp = (*t);
		(*t) = (*(*t)).link[(((NI) 1))- 0];
		(*temp).link[(((NI) 1))- 0] = (*(*t)).link[(((NI) 0))- 0];
		(*(*t)).link[(((NI) 0))- 0] = temp;
		(*(*t)).level += ((NI) 1);
	}
	LA3: ;
}

N_NIMCALL(void, add_30953)(Memregion29888* a, Avlnode29886** t, NI key, NI upperbound) {
	{
		if (!((*t) == bottom_29920)) goto LA3;
		(*t) = allocavlnode_30227(a, key, upperbound);
	}
	goto LA1;
	LA3: ;
	{
		{
			if (!((NU64)(key) < (NU64)((*(*t)).key))) goto LA8;
			add_30953(a, &(*(*t)).link[(((NI) 0))- 0], key, upperbound);
		}
		goto LA6;
		LA8: ;
		{
			if (!((NU64)((*(*t)).key) < (NU64)(key))) goto LA11;
			add_30953(a, &(*(*t)).link[(((NI) 1))- 0], key, upperbound);
		}
		goto LA6;
		LA11: ;
		{
		}
		LA6: ;
		skew_30934(t);
		split_30939(t);
	}
	LA1: ;
}

N_NIMCALL(void*, rawalloc_37068)(Memregion29888* a, NI requestedsize) {
	void* result;
	NI size;
	result = 0;
	size = roundup_28401(requestedsize, ((NI) 8));
	{
		NI s;
		Smallchunk29840* c;
		if (!(size <= (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk29840)) - ((NI) 8))))) goto LA3;
		s = (NI)(size / ((NI) 8));
		c = (*a).freesmallchunks[(s)- 0];
		{
			if (!(c == NIM_NIL)) goto LA7;
			c = getsmallchunk_36412(a);
			(*c).freelist = NIM_NIL;
			(*c).Sup.size = size;
			(*c).acc = size;
			(*c).free = (NI)((NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk29840)) - ((NI) 8))) - size);
			(*c).next = NIM_NIL;
			(*c).prev = NIM_NIL;
			listadd_38016(&(*a).freesmallchunks[(s)- 0], c);
			result = ((void*) ((&(*c).data)));
		}
		goto LA5;
		LA7: ;
		{
			{
				if (!((*c).freelist == NIM_NIL)) goto LA12;
				result = ((void*) ((NI)((NU64)(((NI) ((&(*c).data)))) + (NU64)((*c).acc))));
				(*c).acc += size;
			}
			goto LA10;
			LA12: ;
			{
				result = ((void*) ((*c).freelist));
				(*c).freelist = (*(*c).freelist).next;
			}
			LA10: ;
			(*c).free -= size;
		}
		LA5: ;
		{
			if (!((*c).free < size)) goto LA17;
			listremove_40802(&(*a).freesmallchunks[(s)- 0], c);
		}
		LA17: ;
	}
	goto LA1;
	LA3: ;
	{
		Bigchunk29842* c;
		size = roundup_28401((NI)(requestedsize + (NI)(((NI)sizeof(Bigchunk29842)) - ((NI) 8))), ((NI) 4096));
		c = getbigchunk_35614(a, size);
		result = ((void*) ((&(*c).data)));
		{
			if (!((*a).root == NIM_NIL)) goto LA22;
			(*a).root = bottom_29920;
		}
		LA22: ;
		add_30953(a, &(*a).root, ((NI) (result)), (NI)((NU64)(((NI) (result))) + (NU64)(size)));
	}
	LA1: ;
	return result;
}

N_NIMCALL(void*, alloc_46240)(Memregion29888* allocator, NI size) {
	void* result;
	result = 0;
	result = rawalloc_37068(allocator, (NI)(((NI) (size)) + ((NI)sizeof(Freecell29830))));
	(*((Freecell29830*) (result))).zerofield = ((NI) 1);
	result = ((void*) ((NI)((NU64)(((NI) (result))) + (NU64)(((NI)sizeof(Freecell29830))))));
	return result;
}

N_NIMCALL(void*, alloc0_46416)(Memregion29888* allocator, NI size) {
	void* result;
	result = 0;
	result = alloc_46240(allocator, size);
	zeroMem(result, size);
	return result;
}

N_NOCONV(void*, alloc0_7417)(NI size) {
	void* result;
	result = 0;
	result = alloc0_46416((&gch_50059.region), size);
	return result;
}

N_NIMCALL(void, init_47803)(Cellseq47721* s, NI cap) {
	void* LOC1;
	(*s).len = ((NI) 0);
	(*s).cap = cap;
	LOC1 = 0;
	LOC1 = alloc0_7417(((NI) ((NI)(cap * ((NI) 8)))));
	(*s).d = ((Cell47705**) (LOC1));
}

N_NIMCALL(void, init_47818)(Cellset47717* s) {
	void* LOC1;
	LOC1 = 0;
	LOC1 = alloc0_7417(((NI) 8192));
	(*s).data = ((Pagedesc47713**) (LOC1));
	(*s).max = ((NI) 1023);
	(*s).counter = ((NI) 0);
	(*s).head = NIM_NIL;
}

N_NIMCALL(void, initgc_11401)(void) {
	gch_50059.cyclethreshold = ((NI) 4194304);
	gch_50059.stat.stackscans = ((NI) 0);
	gch_50059.stat.cyclecollections = ((NI) 0);
	gch_50059.stat.maxthreshold = ((NI) 0);
	gch_50059.stat.maxstacksize = ((NI) 0);
	gch_50059.stat.maxstackcells = ((NI) 0);
	gch_50059.stat.cycletablesize = ((NI) 0);
	init_47803((&gch_50059.zct), ((NI) 1024));
	init_47803((&gch_50059.tempstack), ((NI) 1024));
	init_47818((&gch_50059.cycleroots));
	init_47803((&gch_50059.decstack), ((NI) 1024));
}

N_NOINLINE(NI, stacksize_71801)(void) {
	NI result;
	void* volatile stacktop;
	result = 0;
	stacktop = 0;
	result = ((NI)(((NI) ((&stacktop))) - ((NI) (gch_50059.stackbottom))) > 0? ((NI)(((NI) ((&stacktop))) - ((NI) (gch_50059.stackbottom)))) : -((NI)(((NI) ((&stacktop))) - ((NI) (gch_50059.stackbottom)))));
	return result;
}

static N_INLINE(NI, getoccupiedmem_47630)(Memregion29888* a) {
	NI result;
	result = 0;
	result = (NI)((*a).currmem - (*a).freemem);
	return result;
}

N_NIMCALL(NI, lowgauge_30812)(Avlnode29886* n) {
	NI result;
	Avlnode29886* it;
	result = 0;
	it = n;
	{
		while (1) {
			if (!!((it == bottom_29920))) goto LA2;
			result = (*it).key;
			it = (*it).link[(((NI) 0))- 0];
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NI, highgauge_30829)(Avlnode29886* n) {
	NI result;
	Avlnode29886* it;
	result = 0;
	result = ((NI) -1);
	it = n;
	{
		while (1) {
			if (!!((it == bottom_29920))) goto LA2;
			result = (*it).upperbound;
			it = (*it).link[(((NI) 1))- 0];
		} LA2: ;
	}
	return result;
}

static N_INLINE(void, prepareforinteriorpointerchecking_45088)(Memregion29888* a) {
	(*a).minlargeobj = lowgauge_30812((*a).root);
	(*a).maxlargeobj = highgauge_30829((*a).root);
}

static N_INLINE(Cell47705*, usrtocell_51640)(void* usr) {
	Cell47705* result;
	result = 0;
	result = ((Cell47705*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47705))))));
	return result;
}

static N_INLINE(Basechunk29838*, pageaddr_31580)(void* p) {
	Basechunk29838* result;
	result = 0;
	result = ((Basechunk29838*) ((NI)(((NI) (p)) & ((NI) -4096))));
	return result;
}

static N_INLINE(NIM_BOOL, chunkunused_31489)(Basechunk29838* c) {
	NIM_BOOL result;
	result = 0;
	result = !((*c).used);
	return result;
}

static N_INLINE(NIM_BOOL, issmallchunk_31469)(Basechunk29838* c) {
	NIM_BOOL result;
{	result = 0;
	result = ((*c).size <= (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk29840)) - ((NI) 8))));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Avlnode29886*, inrange_30881)(Avlnode29886* root, NI key) {
	Avlnode29886* result;
	Avlnode29886* it;
{	result = 0;
	it = root;
	{
		while (1) {
			if (!!((it == bottom_29920))) goto LA2;
			{
				NIM_BOOL LOC5;
				LOC5 = 0;
				LOC5 = ((NU64)((*it).key) <= (NU64)(key));
				if (!(LOC5)) goto LA6;
				LOC5 = ((NU64)(key) < (NU64)((*it).upperbound));
				LA6: ;
				if (!LOC5) goto LA7;
				result = it;
				goto BeforeRet;
			}
			LA7: ;
			it = (*it).link[(((NU64)((*it).key) < (NU64)(key)))- 0];
		} LA2: ;
	}
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void*, interiorallocatedptr_45092)(Memregion29888* a, void* p) {
	void* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		Basechunk29838* c_45097;
		LOC3 = 0;
		LOC3 = isaccessible_32415(a, p);
		if (!LOC3) goto LA4;
		c_45097 = pageaddr_31580(p);
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = chunkunused_31489(c_45097);
			if (!!(LOC8)) goto LA9;
			{
				NIM_BOOL LOC13;
				Smallchunk29840* c;
				NI offset;
				LOC13 = 0;
				LOC13 = issmallchunk_31469(c_45097);
				if (!LOC13) goto LA14;
				c = ((Smallchunk29840*) (c_45097));
				offset = (NI)((NU64)(((NI) ((NI)(((NI) (p)) & ((NI) 4095))))) - (NU64)((NI)(((NI)sizeof(Smallchunk29840)) - ((NI) 8))));
				{
					Freecell29830* d;
					if (!((NU64)(offset) < (NU64)((*c).acc))) goto LA18;
					d = ((Freecell29830*) ((NI)((NU64)((NI)((NU64)(((NI) ((&(*c).data)))) + (NU64)(offset))) - (NU64)((NI)((NU64)(offset) % (NU64)((*c).Sup.size))))));
					{
						if (!((NU64)(((NI) 1)) < (NU64)((*d).zerofield))) goto LA22;
						result = ((void*) (d));
					}
					LA22: ;
				}
				LA18: ;
			}
			goto LA11;
			LA14: ;
			{
				Bigchunk29842* c;
				NF* d;
				c = ((Bigchunk29842*) (c_45097));
				d = (&(*c).data);
				{
					NIM_BOOL LOC27;
					LOC27 = 0;
					LOC27 = (((void*) (d)) <= p);
					if (!(LOC27)) goto LA28;
					LOC27 = ((NU64)(((NI) 1)) < (NU64)((*((Freecell29830*) (d))).zerofield));
					LA28: ;
					if (!LOC27) goto LA29;
					result = ((void*) (d));
				}
				LA29: ;
			}
			LA11: ;
		}
		LA9: ;
	}
	goto LA1;
	LA4: ;
	{
		NI q;
		q = ((NI) (p));
		{
			NIM_BOOL LOC34;
			Avlnode29886* avlnode;
			LOC34 = 0;
			LOC34 = ((NU64)((*a).minlargeobj) <= (NU64)(q));
			if (!(LOC34)) goto LA35;
			LOC34 = ((NU64)(q) <= (NU64)((*a).maxlargeobj));
			LA35: ;
			if (!LOC34) goto LA36;
			avlnode = inrange_30881((*a).root, q);
			{
				void* k;
				Bigchunk29842* c;
				Basechunk29838* LOC42;
				if (!!((avlnode == NIM_NIL))) goto LA40;
				k = ((void*) ((*avlnode).key));
				LOC42 = 0;
				LOC42 = pageaddr_31580(k);
				c = ((Bigchunk29842*) (LOC42));
				{
					if (!((NU64)(((NI) 1)) < (NU64)((*((Freecell29830*) (k))).zerofield))) goto LA45;
					result = k;
				}
				LA45: ;
			}
			LA40: ;
		}
		LA36: ;
	}
	LA1: ;
	return result;
}

N_NOCONV(void*, alloc_7401)(NI size) {
	void* result;
	result = 0;
	result = alloc_46240((&gch_50059.region), size);
	return result;
}

N_NIMCALL(void, excl_31164)(Intset29814* s, NI key) {
	Trunk29810* t;
	t = intsetget_31083((&(*s)), (NI)((NU64)(key) >> (NU64)(((NI) 9))));
	{
		NI u;
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)(key & ((NI) 511));
		(*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64) ~((NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63)))))))));
	}
	LA3: ;
}

static N_INLINE(void, osdeallocpages_29621)(void* p, NI size) {
	munmap(p, size);
}

static N_INLINE(void, deccurrmem_30016)(Memregion29888* a, NI bytes) {
	(*a).maxmem = (((*a).maxmem >= (*a).currmem) ? (*a).maxmem : (*a).currmem);
	(*a).currmem -= bytes;
}

N_NIMCALL(void, freeoschunks_32207)(Memregion29888* a, void* p, NI size) {
	Basechunk29838* c;
	NI nxt;
	Basechunk29838* next;
	NI LOC7;
	c = ((Basechunk29838*) (p));
	nxt = (NI)((NU64)(((NI) (p))) + (NU64)((*c).size));
	next = ((Basechunk29838*) (nxt));
	{
		NI LOC3;
		NIM_BOOL LOC4;
		LOC3 = 0;
		LOC3 = pageindex_31570(next);
		LOC4 = 0;
		LOC4 = contains_31132((&(*a).chunkstarts), LOC3);
		if (!LOC4) goto LA5;
		(*next).prevsize = ((NI) 0);
	}
	LA5: ;
	LOC7 = 0;
	LOC7 = pageindex_31575(p);
	excl_31164((&(*a).chunkstarts), LOC7);
	osdeallocpages_29621(p, size);
	deccurrmem_30016(a, size);
	(*a).freemem -= size;
}

N_NIMCALL(void, freebigchunk_32603)(Memregion29888* a, Bigchunk29842* c_32607) {
	Bigchunk29842* c;
	Basechunk29838* ri;
	c = c_32607;
	(*a).freemem += (*c).Sup.size;
	ri = ((Basechunk29838*) ((NI)((NU64)(((NI) (c))) + (NU64)((*c).Sup.size))));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isaccessible_32415((&(*a)), ((void*) (ri)));
		if (!(LOC3)) goto LA4;
		LOC3 = chunkunused_31489(ri);
		LA4: ;
		if (!LOC3) goto LA5;
		{
			NIM_BOOL LOC9;
			NI LOC12;
			LOC9 = 0;
			LOC9 = issmallchunk_31469(ri);
			if (!!(LOC9)) goto LA10;
			listremove_33402(&(*a).freechunkslist, ((Bigchunk29842*) (ri)));
			(*c).Sup.size += (*ri).size;
			LOC12 = 0;
			LOC12 = pageindex_31570(ri);
			excl_31164((&(*a).chunkstarts), LOC12);
		}
		LA10: ;
	}
	LA5: ;
	{
		Basechunk29838* le;
		if (!!(((*c).Sup.prevsize == ((NI) 0)))) goto LA15;
		le = ((Basechunk29838*) ((NI)((NU64)(((NI) (c))) - (NU64)((*c).Sup.prevsize))));
		{
			NIM_BOOL LOC19;
			LOC19 = 0;
			LOC19 = isaccessible_32415((&(*a)), ((void*) (le)));
			if (!(LOC19)) goto LA20;
			LOC19 = chunkunused_31489(le);
			LA20: ;
			if (!LOC19) goto LA21;
			{
				NIM_BOOL LOC25;
				Basechunk29838* LOC28;
				NI LOC29;
				LOC25 = 0;
				LOC25 = issmallchunk_31469(le);
				if (!!(LOC25)) goto LA26;
				listremove_33402(&(*a).freechunkslist, ((Bigchunk29842*) (le)));
				(*le).size += (*c).Sup.size;
				LOC28 = 0;
				LOC28 = &c->Sup;
				LOC29 = 0;
				LOC29 = pageindex_31570(LOC28);
				excl_31164((&(*a).chunkstarts), LOC29);
				c = ((Bigchunk29842*) (le));
			}
			LA26: ;
		}
		LA21: ;
	}
	LA15: ;
	{
		NIM_BOOL LOC32;
		Basechunk29838* LOC36;
		NI LOC37;
		LOC32 = 0;
		LOC32 = ((*c).Sup.size < ((NI) 1048576));
		if (LOC32) goto LA33;
		LOC32 = NIM_FALSE;
		LA33: ;
		if (!LOC32) goto LA34;
		LOC36 = 0;
		LOC36 = &c->Sup;
		LOC37 = 0;
		LOC37 = pageindex_31570(LOC36);
		incl_31153(a, (&(*a).chunkstarts), LOC37);
		updateprevsize_32468(a, c, (*c).Sup.size);
		listadd_34623(&(*a).freechunkslist, c);
		(*c).Sup.used = NIM_FALSE;
	}
	goto LA30;
	LA34: ;
	{
		freeoschunks_32207(a, ((void*) (c)), (*c).Sup.size);
	}
	LA30: ;
}

static N_INLINE(void, deallocavlnode_30803)(Memregion29888* a, Avlnode29886* n) {
	(*n).link[(((NI) 0))- 0] = (*a).freeavlnodes;
	(*a).freeavlnodes = n;
}

N_NIMCALL(void, del_31001)(Memregion29888* a, Avlnode29886** t, NI x) {
{	{
		if (!((*t) == bottom_29920)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	(*a).last = (*t);
	{
		if (!((NU64)(x) < (NU64)((*(*t)).key))) goto LA7;
		del_31001(a, &(*(*t)).link[(((NI) 0))- 0], x);
	}
	goto LA5;
	LA7: ;
	{
		(*a).deleted = (*t);
		del_31001(a, &(*(*t)).link[(((NI) 1))- 0], x);
	}
	LA5: ;
	{
		NIM_BOOL LOC12;
		NIM_BOOL LOC13;
		LOC12 = 0;
		LOC13 = 0;
		LOC13 = ((*t) == (*a).last);
		if (!(LOC13)) goto LA14;
		LOC13 = !(((*a).deleted == bottom_29920));
		LA14: ;
		LOC12 = LOC13;
		if (!(LOC12)) goto LA15;
		LOC12 = (x == (*(*a).deleted).key);
		LA15: ;
		if (!LOC12) goto LA16;
		(*(*a).deleted).key = (*(*t)).key;
		(*(*a).deleted).upperbound = (*(*t)).upperbound;
		(*a).deleted = bottom_29920;
		(*t) = (*(*t)).link[(((NI) 1))- 0];
		deallocavlnode_30803(a, (*a).last);
	}
	goto LA10;
	LA16: ;
	{
		NIM_BOOL LOC19;
		LOC19 = 0;
		LOC19 = ((*(*(*t)).link[(((NI) 0))- 0]).level < (NI)((*(*t)).level - ((NI) 1)));
		if (LOC19) goto LA20;
		LOC19 = ((*(*(*t)).link[(((NI) 1))- 0]).level < (NI)((*(*t)).level - ((NI) 1)));
		LA20: ;
		if (!LOC19) goto LA21;
		(*(*t)).level -= ((NI) 1);
		{
			if (!((*(*t)).level < (*(*(*t)).link[(((NI) 1))- 0]).level)) goto LA25;
			(*(*(*t)).link[(((NI) 1))- 0]).level = (*(*t)).level;
		}
		LA25: ;
		skew_30934(t);
		skew_30934(&(*(*t)).link[(((NI) 1))- 0]);
		skew_30934(&(*(*(*t)).link[(((NI) 1))- 0]).link[(((NI) 1))- 0]);
		split_30939(t);
		split_30939(&(*(*t)).link[(((NI) 1))- 0]);
	}
	goto LA10;
	LA21: ;
	LA10: ;
	}BeforeRet: ;
}

N_NIMCALL(void, rawdealloc_43417)(Memregion29888* a, void* p) {
	Basechunk29838* c_43601;
	c_43601 = pageaddr_31580(p);
	{
		NIM_BOOL LOC3;
		Smallchunk29840* c;
		NI s;
		Freecell29830* f;
		LOC3 = 0;
		LOC3 = issmallchunk_31469(c_43601);
		if (!LOC3) goto LA4;
		c = ((Smallchunk29840*) (c_43601));
		s = (*c).Sup.size;
		f = ((Freecell29830*) (p));
		(*f).zerofield = ((NI) 0);
		(*f).next = (*c).freelist;
		(*c).freelist = f;
		{
			if (!((*c).free < s)) goto LA8;
			listadd_38016(&(*a).freesmallchunks[((NI)(s / ((NI) 8)))- 0], c);
			(*c).free += s;
		}
		goto LA6;
		LA8: ;
		{
			(*c).free += s;
			{
				if (!((*c).free == (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk29840)) - ((NI) 8))))) goto LA13;
				listremove_40802(&(*a).freesmallchunks[((NI)(s / ((NI) 8)))- 0], c);
				(*c).Sup.size = ((NI) 4096);
				freebigchunk_32603(a, ((Bigchunk29842*) (c)));
			}
			LA13: ;
		}
		LA6: ;
	}
	goto LA1;
	LA4: ;
	{
		Bigchunk29842* c;
		c = ((Bigchunk29842*) (c_43601));
		(*a).deleted = bottom_29920;
		del_31001(a, &(*a).root, ((NI) ((&(*c).data))));
		freebigchunk_32603(a, c);
	}
	LA1: ;
}

N_NIMCALL(void, dealloc_46422)(Memregion29888* allocator, void* p) {
	void* x;
	x = ((void*) ((NI)((NU64)(((NI) (p))) - (NU64)(((NI)sizeof(Freecell29830))))));
	rawdealloc_43417(allocator, x);
}

N_NOCONV(void, dealloc_7448)(void* p) {
	dealloc_46422((&gch_50059.region), p);
}

static N_INLINE(void, add_47783)(Cellseq47721* s, Cell47705* c) {
	{
		Cell47705** d;
		void* LOC5;
		if (!((*s).cap <= (*s).len)) goto LA3;
		(*s).cap = (NI)((NI)((*s).cap * ((NI) 3)) / ((NI) 2));
		LOC5 = 0;
		LOC5 = alloc_7401(((NI) ((NI)((*s).cap * ((NI) 8)))));
		d = ((Cell47705**) (LOC5));
		memcpy(((void*) (d)), ((void*) ((*s).d)), ((NI) ((NI)((*s).len * ((NI) 8)))));
		dealloc_7448(((void*) ((*s).d)));
		(*s).d = d;
	}
	LA3: ;
	(*s).d[((*s).len)- 0] = c;
	(*s).len += ((NI) 1);
}

static N_INLINE(void, gcmark_70816)(Gcheap50018* gch, void* p) {
	Cell47705* cell;
	NI c;
	cell = usrtocell_51640(p);
	c = ((NI) (cell));
	{
		Cell47705* objstart;
		void* LOC5;
		if (!((NU64)(((NI) 4096)) < (NU64)(c))) goto LA3;
		LOC5 = 0;
		LOC5 = interiorallocatedptr_45092((&(*gch).region), ((void*) (cell)));
		objstart = ((Cell47705*) (LOC5));
		{
			if (!!((objstart == NIM_NIL))) goto LA8;
			(*objstart).refcount = (NI)((NU64)((*objstart).refcount) + (NU64)(((NI) 8)));
			add_47783((&(*gch).decstack), objstart);
		}
		LA8: ;
	}
	LA3: ;
}

N_CDECL(void, markstackandregisters_73037)(Gcheap50018* gch) {
	jmp_buf registers;
	{
		int LOC3;
		NI max;
		NI sp;
		NI regend;
		LOC3 = 0;
		LOC3 = _setjmp(registers);
		if (!(LOC3 == ((NI32) 0))) goto LA4;
		max = ((NI) ((*gch).stackbottom));
		sp = ((NI) ((&registers)));
		regend = (NI)((NU64)(sp) + (NU64)(((NI)sizeof(jmp_buf))));
		{
			while (1) {
				if (!((NU64)(sp) < (NU64)(regend))) goto LA7;
				gcmark_70816(gch, (*((void**) (sp))));
				gcmark_70816(gch, (*((void**) ((NI)((NU64)(sp) + (NU64)(((NI) 4)))))));
				sp = (NI)((NU64)(sp) + (NU64)(((NI) 8)));
			} LA7: ;
		}
		sp = (NI)(sp & ((NI) -8));
		{
			while (1) {
				if (!((NU64)(sp) < (NU64)((NI)(max - ((NI) 64))))) goto LA9;
				gcmark_70816(gch, ((void**) (sp))[(((NI) 0))- 0]);
				gcmark_70816(gch, ((void**) (sp))[(((NI) 1))- 0]);
				gcmark_70816(gch, ((void**) (sp))[(((NI) 2))- 0]);
				gcmark_70816(gch, ((void**) (sp))[(((NI) 3))- 0]);
				gcmark_70816(gch, ((void**) (sp))[(((NI) 4))- 0]);
				gcmark_70816(gch, ((void**) (sp))[(((NI) 5))- 0]);
				gcmark_70816(gch, ((void**) (sp))[(((NI) 6))- 0]);
				gcmark_70816(gch, ((void**) (sp))[(((NI) 7))- 0]);
				sp = (NI)((NU64)(sp) + (NU64)(((NI) 64)));
			} LA9: ;
		}
		{
			while (1) {
				if (!((NU64)(sp) <= (NU64)(max))) goto LA11;
				gcmark_70816(gch, (*((void**) (sp))));
				sp = (NI)((NU64)(sp) + (NU64)(((NI) 8)));
			} LA11: ;
		}
	}
	LA4: ;
}

N_NIMCALL(void, markthreadstacks_71403)(Gcheap50018* gch) {
}

static N_INLINE(NIM_BOOL, canbecycleroot_51658)(Cell47705* c) {
	NIM_BOOL result;
	result = 0;
	result = !((((*(*c).typ).flags &(1U<<((NU)(((NU8) 1))&7U)))!=0));
	return result;
}

static N_INLINE(NI, nexttry_47845)(NI h, NI maxhash) {
	NI result;
	result = 0;
	result = (NI)((NI)((NI)(((NI) 5) * h) + ((NI) 1)) & maxhash);
	return result;
}

N_NIMCALL(Pagedesc47713*, cellsetget_47850)(Cellset47717* t, NI key) {
	Pagedesc47713* result;
	NI h;
{	result = 0;
	h = (NI)(((NI) (key)) & (*t).max);
	{
		while (1) {
			if (!!(((*t).data[(h)- 0] == NIM_NIL))) goto LA2;
			{
				if (!((*(*t).data[(h)- 0]).key == key)) goto LA5;
				result = (*t).data[(h)- 0];
				goto BeforeRet;
			}
			LA5: ;
			h = nexttry_47845(h, (*t).max);
		} LA2: ;
	}
	result = NIM_NIL;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, excl_48474)(Cellset47717* s, Cell47705* cell) {
	NI u;
	Pagedesc47713* t;
	u = ((NI) (cell));
	t = cellsetget_47850((&(*s)), (NI)((NU64)(u) >> (NU64)(((NI) 12))));
	{
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)((NU64)((NI)((NU64)(u) % (NU64)(((NI) 4096)))) / (NU64)(((NI) 8)));
		(*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64) ~((NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(u & ((NI) 63)))))))));
	}
	LA3: ;
}

static N_INLINE(void*, celltousr_51622)(Cell47705* cell) {
	void* result;
	result = 0;
	result = ((void*) ((NI)((NU64)(((NI) (cell))) + (NU64)(((NI)sizeof(Cell47705))))));
	return result;
}

N_NIMCALL(void, preparedealloc_52208)(Cell47705* cell) {
	{
		void* LOC5;
		if (!!(((*(*cell).typ).finalizer == NIM_NIL))) goto LA3;
		gch_50059.recgclock += ((NI) 1);
		LOC5 = 0;
		LOC5 = celltousr_51622(cell);
		((Finalizer) ((*(*cell).typ).finalizer))(LOC5);
		gch_50059.recgclock -= ((NI) 1);
	}
	LA3: ;
}

N_NOINLINE(void, addzct_51617)(Cellseq47721* s, Cell47705* c) {
	{
		if (!((NI)((*c).refcount & ((NI) 4)) == ((NI) 0))) goto LA3;
		(*c).refcount = (NI)((*c).refcount | ((NI) 4));
		add_47783(s, c);
	}
	LA3: ;
}

static N_INLINE(void, rtladdzct_53201)(Cell47705* c) {
	addzct_51617((&gch_50059.zct), c);
}

N_NIMCALL(void, cellsetrawinsert_47870)(Cellset47717* t, Pagedesc47713** data, Pagedesc47713* desc) {
	NI h;
	h = (NI)(((NI) ((*desc).key)) & (*t).max);
	{
		while (1) {
			if (!!((data[(h)- 0] == NIM_NIL))) goto LA2;
			h = nexttry_47845(h, (*t).max);
		} LA2: ;
	}
	data[(h)- 0] = desc;
}

N_NIMCALL(void, cellsetenlarge_48203)(Cellset47717* t) {
	NI oldmax;
	Pagedesc47713** n;
	void* LOC1;
	oldmax = (*t).max;
	(*t).max = (NI)((NI)((NI)((*t).max + ((NI) 1)) * ((NI) 2)) - ((NI) 1));
	LOC1 = 0;
	LOC1 = alloc0_7417(((NI) ((NI)((NI)((*t).max + ((NI) 1)) * ((NI) 8)))));
	n = ((Pagedesc47713**) (LOC1));
	{
		NI i_48219;
		NI res_48237;
		i_48219 = 0;
		res_48237 = ((NI) 0);
		{
			while (1) {
				if (!(res_48237 <= oldmax)) goto LA4;
				i_48219 = res_48237;
				{
					if (!!(((*t).data[(i_48219)- 0] == NIM_NIL))) goto LA7;
					cellsetrawinsert_47870((&(*t)), n, (*t).data[(i_48219)- 0]);
				}
				LA7: ;
				res_48237 += ((NI) 1);
			} LA4: ;
		}
	}
	dealloc_7448(((void*) ((*t).data)));
	(*t).data = n;
}

N_NIMCALL(Pagedesc47713*, cellsetput_48241)(Cellset47717* t, NI key) {
	Pagedesc47713* result;
	NI h;
	void* LOC19;
{	result = 0;
	h = (NI)(((NI) (key)) & (*t).max);
	{
		while (1) {
			Pagedesc47713* x;
			x = (*t).data[(h)- 0];
			{
				if (!(x == NIM_NIL)) goto LA5;
				goto LA1;
			}
			LA5: ;
			{
				if (!((*x).key == key)) goto LA9;
				result = x;
				goto BeforeRet;
			}
			LA9: ;
			h = nexttry_47845(h, (*t).max);
		}
	} LA1: ;
	{
		NIM_BOOL LOC13;
		LOC13 = 0;
		LOC13 = ((NI)((NI)((*t).max + ((NI) 1)) * ((NI) 2)) < (NI)((*t).counter * ((NI) 3)));
		if (LOC13) goto LA14;
		LOC13 = ((NI)((NI)((*t).max + ((NI) 1)) - (*t).counter) < ((NI) 4));
		LA14: ;
		if (!LOC13) goto LA15;
		cellsetenlarge_48203(t);
	}
	LA15: ;
	(*t).counter += ((NI) 1);
	h = (NI)(((NI) (key)) & (*t).max);
	{
		while (1) {
			if (!!(((*t).data[(h)- 0] == NIM_NIL))) goto LA18;
			h = nexttry_47845(h, (*t).max);
		} LA18: ;
	}
	LOC19 = 0;
	LOC19 = alloc0_7417(((NI) (((NI)sizeof(Pagedesc47713)))));
	result = ((Pagedesc47713*) (LOC19));
	(*result).next = (*t).head;
	(*result).key = key;
	(*t).head = result;
	(*t).data[(h)- 0] = result;
	}BeforeRet: ;
	return result;
}

N_NOINLINE(void, incl_48447)(Cellset47717* s, Cell47705* cell) {
	NI u;
	Pagedesc47713* t;
	u = ((NI) (cell));
	t = cellsetput_48241(s, (NI)((NU64)(u) >> (NU64)(((NI) 12))));
	u = (NI)((NU64)((NI)((NU64)(u) % (NU64)(((NI) 4096)))) / (NU64)(((NI) 8)));
	(*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(u & ((NI) 63)))))));
}

static N_INLINE(void, rtladdcycleroot_52420)(Cell47705* c) {
	{
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		incl_48447((&gch_50059.cycleroots), c);
	}
	LA3: ;
}

static N_INLINE(void, decref_53601)(Cell47705* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_53201(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = 0;
		LOC6 = canbecycleroot_51658(c);
		if (!LOC6) goto LA7;
		rtladdcycleroot_52420(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
}

N_NIMCALL(void, markgray_67202)(Cell47705* s) {
	{
		if (!!((((NI) ((NI)((*s).refcount & ((NI) 3)))) == ((NI) 1)))) goto LA3;
		(*s).refcount = (NI)((NI)((*s).refcount & ((NI) -4)) | ((NI) 1));
		forallchildren_52014(s, ((NU8) 5));
	}
	LA3: ;
}

N_NIMCALL(void, scanblack_67401)(Cell47705* s) {
	(*s).refcount = (NI)((*s).refcount & ((NI) -4));
	forallchildren_52014(s, ((NU8) 7));
}

N_NIMCALL(void, scan_67601)(Cell47705* s) {
	{
		if (!(((NI) ((NI)((*s).refcount & ((NI) 3)))) == ((NI) 1))) goto LA3;
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*s).refcount))) goto LA7;
			scanblack_67401(s);
		}
		goto LA5;
		LA7: ;
		{
			(*s).refcount = (NI)((NI)((*s).refcount & ((NI) -4)) | ((NI) 2));
			forallchildren_52014(s, ((NU8) 6));
		}
		LA5: ;
	}
	LA3: ;
}

N_NIMCALL(NIM_BOOL, isallocatedptr_36802)(Memregion29888* a, void* p) {
	NIM_BOOL result;
	result = 0;
	{
		NIM_BOOL LOC3;
		Basechunk29838* c_45013;
		LOC3 = 0;
		LOC3 = isaccessible_32415(a, p);
		if (!LOC3) goto LA4;
		c_45013 = pageaddr_31580(p);
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = chunkunused_31489(c_45013);
			if (!!(LOC8)) goto LA9;
			{
				NIM_BOOL LOC13;
				Smallchunk29840* c;
				NI offset;
				NIM_BOOL LOC16;
				NIM_BOOL LOC17;
				LOC13 = 0;
				LOC13 = issmallchunk_31469(c_45013);
				if (!LOC13) goto LA14;
				c = ((Smallchunk29840*) (c_45013));
				offset = (NI)((NU64)(((NI) ((NI)(((NI) (p)) & ((NI) 4095))))) - (NU64)((NI)(((NI)sizeof(Smallchunk29840)) - ((NI) 8))));
				LOC16 = 0;
				LOC17 = 0;
				LOC17 = ((NU64)(offset) < (NU64)((*c).acc));
				if (!(LOC17)) goto LA18;
				LOC17 = ((NI)((NU64)(offset) % (NU64)((*c).Sup.size)) == ((NI) 0));
				LA18: ;
				LOC16 = LOC17;
				if (!(LOC16)) goto LA19;
				LOC16 = ((NU64)(((NI) 1)) < (NU64)((*((Freecell29830*) (p))).zerofield));
				LA19: ;
				result = LOC16;
			}
			goto LA11;
			LA14: ;
			{
				Bigchunk29842* c;
				NIM_BOOL LOC21;
				c = ((Bigchunk29842*) (c_45013));
				LOC21 = 0;
				LOC21 = (p == ((void*) ((&(*c).data))));
				if (!(LOC21)) goto LA22;
				LOC21 = ((NU64)(((NI) 1)) < (NU64)((*((Freecell29830*) (p))).zerofield));
				LA22: ;
				result = LOC21;
			}
			LA11: ;
		}
		LA9: ;
	}
	LA4: ;
	return result;
}

N_NIMCALL(void, freecycliccell_66415)(Gcheap50018* gch, Cell47705* c) {
	preparedealloc_52208(c);
	rawdealloc_43417((&(*gch).region), ((void*) (c)));
}

N_NIMCALL(void, collectwhite_67801)(Cell47705* s) {
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isallocatedptr_36802((&gch_50059.region), ((void*) (s)));
		if (!(LOC3)) goto LA4;
		LOC3 = (((NI) ((NI)((*s).refcount & ((NI) 3)))) == ((NI) 2));
		LA4: ;
		if (!LOC3) goto LA5;
		(*s).refcount = (NI)((*s).refcount & ((NI) -4));
		forallchildren_52014(s, ((NU8) 8));
		freecycliccell_66415((&gch_50059), s);
	}
	LA5: ;
}

N_NIMCALL(void, dooperation_52018)(void* p, NU8 op) {
	Cell47705* c;
{	{
		if (!(p == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	c = usrtocell_51640(p);
	switch (op) {
	case ((NU8) 2):
	{
		decref_53601(c);
	}
	break;
	case ((NU8) 3):
	{
		add_47783((&gch_50059.tempstack), c);
	}
	break;
	case ((NU8) 4):
	{
		(*c).refcount = (NI)((NU64)((*c).refcount) - (NU64)(((NI) 8)));
	}
	break;
	case ((NU8) 5):
	{
		(*c).refcount = (NI)((NU64)((*c).refcount) - (NU64)(((NI) 8)));
		markgray_67202(c);
	}
	break;
	case ((NU8) 6):
	{
		scan_67601(c);
	}
	break;
	case ((NU8) 7):
	{
		(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
		{
			if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 0)))) goto LA13;
			scanblack_67401(c);
		}
		LA13: ;
	}
	break;
	case ((NU8) 8):
	{
		collectwhite_67801(c);
	}
	break;
	case ((NU8) 0):
	{
	}
	break;
	case ((NU8) 1):
	{
	}
	break;
	}
	}BeforeRet: ;
}

N_NIMCALL(NI, getdiscriminant_27404)(void* aa, TNimNode* n) {
	NI result;
	NI d;
	NI a;
{	result = 0;
	d = 0;
	a = ((NI) (aa));
	switch ((*(*n).typ).size) {
	case ((NI) 1):
	{
		d = ((NI)(NU)(NU8)((*((NI8*) ((NI)((NU64)(a) + (NU64)((*n).offset)))))));
	}
	break;
	case ((NI) 2):
	{
		d = ((NI)(NU)(NU16)((*((NI16*) ((NI)((NU64)(a) + (NU64)((*n).offset)))))));
	}
	break;
	case ((NI) 4):
	{
		d = ((NI) ((*((NI32*) ((NI)((NU64)(a) + (NU64)((*n).offset)))))));
	}
	break;
	default:
	{
	}
	break;
	}
	result = d;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(TNimNode*, selectbranch_27807)(void* aa, TNimNode* n) {
	TNimNode* result;
	NI discr;
	result = 0;
	discr = getdiscriminant_27404(aa, n);
	{
		if (!((NU64)(discr) < (NU64)((*n).len))) goto LA3;
		result = (*n).sons[(discr)- 0];
		{
			if (!(result == NIM_NIL)) goto LA7;
			result = (*n).sons[((*n).len)- 0];
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).sons[((*n).len)- 0];
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, forallslotsaux_56205)(void* dest, TNimNode* n, NU8 op) {
	NI d;
	d = ((NI) (dest));
	switch ((*n).kind) {
	case ((NU8) 1):
	{
		forallchildrenaux_52022(((void*) ((NI)((NU64)(d) + (NU64)((*n).offset)))), (*n).typ, op);
	}
	break;
	case ((NU8) 2):
	{
		{
			NI i_56230;
			NI HEX3Atmp_56406;
			NI res_56409;
			i_56230 = 0;
			HEX3Atmp_56406 = 0;
			HEX3Atmp_56406 = (NI)((*n).len - ((NI) 1));
			res_56409 = ((NI) 0);
			{
				while (1) {
					if (!(res_56409 <= HEX3Atmp_56406)) goto LA5;
					i_56230 = res_56409;
					{
						if (!((*(*n).sons[(i_56230)- 0]).kind == ((NU8) 1))) goto LA8;
						{
							if (!((289406976 &((NU64)1<<((NU)((*(*(*n).sons[(i_56230)- 0]).typ).kind)&63U)))!=0)) goto LA12;
							dooperation_52018((*((void**) ((NI)((NU64)(d) + (NU64)((*(*n).sons[(i_56230)- 0]).offset))))), op);
						}
						goto LA10;
						LA12: ;
						{
							forallchildrenaux_52022(((void*) ((NI)((NU64)(d) + (NU64)((*(*n).sons[(i_56230)- 0]).offset)))), (*(*n).sons[(i_56230)- 0]).typ, op);
						}
						LA10: ;
					}
					goto LA6;
					LA8: ;
					{
						forallslotsaux_56205(dest, (*n).sons[(i_56230)- 0], op);
					}
					LA6: ;
					res_56409 += ((NI) 1);
				} LA5: ;
			}
		}
	}
	break;
	case ((NU8) 3):
	{
		TNimNode* m;
		m = selectbranch_27807(dest, n);
		{
			if (!!((m == NIM_NIL))) goto LA19;
			forallslotsaux_56205(dest, m, op);
		}
		LA19: ;
	}
	break;
	case ((NU8) 0):
	{
	}
	break;
	}
}

N_NIMCALL(void, forallchildrenaux_52022)(void* dest, TNimType* mt, NU8 op) {
	NI d;
{	d = ((NI) (dest));
	{
		if (!(dest == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!!((((*mt).flags &(1U<<((NU)(((NU8) 0))&7U)))!=0))) goto LA7;
		switch ((*mt).kind) {
		case ((NU8) 22):
		case ((NU8) 28):
		case ((NU8) 24):
		{
			dooperation_52018((*((void**) (d))), op);
		}
		break;
		case ((NU8) 17):
		case ((NU8) 18):
		{
			forallslotsaux_56205(dest, (*mt).node, op);
		}
		break;
		case ((NU8) 16):
		case ((NU8) 4):
		case ((NU8) 27):
		{
			{
				NI i_56438;
				NI HEX3Atmp_56461;
				NI res_56464;
				i_56438 = 0;
				HEX3Atmp_56461 = 0;
				HEX3Atmp_56461 = (NI)((NI)((*mt).size / (*(*mt).base).size) - ((NI) 1));
				res_56464 = ((NI) 0);
				{
					while (1) {
						if (!(res_56464 <= HEX3Atmp_56461)) goto LA14;
						i_56438 = res_56464;
						forallchildrenaux_52022(((void*) ((NI)((NU64)(d) + (NU64)((NI)((NU64)(i_56438) * (NU64)((*(*mt).base).size)))))), (*mt).base, op);
						res_56464 += ((NI) 1);
					} LA14: ;
				}
			}
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA7: ;
	}BeforeRet: ;
}

N_NIMCALL(void, forallchildren_52014)(Cell47705* cell, NU8 op) {
	TY3489 marker;
	marker = (*(*cell).typ).marker;
	{
		void* LOC5;
		if (!!((marker == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = celltousr_51622(cell);
		marker(LOC5, ((NI) (op)));
	}
	goto LA1;
	LA3: ;
	{
		switch ((*(*cell).typ).kind) {
		case ((NU8) 22):
		{
			void* LOC8;
			LOC8 = 0;
			LOC8 = celltousr_51622(cell);
			forallchildrenaux_52022(LOC8, (*(*cell).typ).base, op);
		}
		break;
		case ((NU8) 24):
		{
			NI d;
			void* LOC10;
			TGenericSeq* s;
			LOC10 = 0;
			LOC10 = celltousr_51622(cell);
			d = ((NI) (LOC10));
			s = ((TGenericSeq*) (d));
			{
				if (!!((s == NIM_NIL))) goto LA13;
				{
					NI i_57234;
					NI HEX3Atmp_57267;
					NI res_57270;
					i_57234 = 0;
					HEX3Atmp_57267 = 0;
					HEX3Atmp_57267 = (NI)((*s).len - ((NI) 1));
					res_57270 = ((NI) 0);
					{
						while (1) {
							if (!(res_57270 <= HEX3Atmp_57267)) goto LA17;
							i_57234 = res_57270;
							forallchildrenaux_52022(((void*) ((NI)((NU64)((NI)((NU64)(d) + (NU64)((NI)((NU64)(i_57234) * (NU64)((*(*(*cell).typ).base).size))))) + (NU64)(((NI) 16))))), (*(*cell).typ).base, op);
							res_57270 += ((NI) 1);
						} LA17: ;
					}
				}
			}
			LA13: ;
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA1: ;
}

N_NIMCALL(NIM_BOOL, collectzct_70206)(Gcheap50018* gch) {
	NIM_BOOL result;
	NI* L;
	result = 0;
	L = (&(*gch).zct.len);
	{
		while (1) {
			Cell47705* c;
			if (!(((NI) 0) < (*L))) goto LA2;
			c = (*gch).zct.d[(((NI) 0))- 0];
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			(*gch).zct.d[(((NI) 0))- 0] = (*gch).zct.d[((NI)((*L) - ((NI) 1)))- 0];
			(*L) -= ((NI) 1);
			{
				if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA5;
				{
					NIM_BOOL LOC9;
					LOC9 = 0;
					LOC9 = canbecycleroot_51658(c);
					if (!LOC9) goto LA10;
					excl_48474((&(*gch).cycleroots), c);
				}
				LA10: ;
				preparedealloc_52208(c);
				forallchildren_52014(c, ((NU8) 2));
				rawdealloc_43417((&(*gch).region), ((void*) (c)));
			}
			LA5: ;
		} LA2: ;
	}
	result = NIM_TRUE;
	return result;
}

N_NIMCALL(void, markroots_68002)(Gcheap50018* gch) {
	NI tabsize;
	tabsize = ((NI) 0);
	{
		Cell47705* s_68007;
		Cellset47717 HEX3Atmp_68034;
		Pagedesc47713* r_68039;
		s_68007 = 0;
		memset((void*)(&HEX3Atmp_68034), 0, sizeof(HEX3Atmp_68034));
		HEX3Atmp_68034 = (*gch).cycleroots;
		r_68039 = HEX3Atmp_68034.head;
		{
			while (1) {
				NI i_68041;
				if (!!((r_68039 == NIM_NIL))) goto LA3;
				i_68041 = ((NI) 0);
				{
					while (1) {
						NI w_68043;
						NI j_68045;
						if (!(i_68041 <= ((NI) 7))) goto LA5;
						w_68043 = (*r_68039).bits[(i_68041)- 0];
						j_68045 = ((NI) 0);
						{
							while (1) {
								if (!!((w_68043 == ((NI) 0)))) goto LA7;
								{
									if (!!((((NI) ((NI)(w_68043 & ((NI) 1)))) == ((NI) 0)))) goto LA10;
									s_68007 = ((Cell47705*) ((NI)((NI)((NU64)((*r_68039).key) << (NU64)(((NI) 12))) | (NI)((NU64)((NI)((NU64)((NI)((NU64)(i_68041) << (NU64)(((NI) 6)))) + (NU64)(j_68045))) * (NU64)(((NI) 8))))));
									tabsize += ((NI) 1);
									{
										NIM_BOOL LOC14;
										LOC14 = 0;
										LOC14 = (((NI) ((NI)((*s_68007).refcount & ((NI) 3)))) == ((NI) 3));
										if (!(LOC14)) goto LA15;
										LOC14 = ((NU64)(((NI) 8)) <= (NU64)((*s_68007).refcount));
										LA15: ;
										if (!LOC14) goto LA16;
										markgray_67202(s_68007);
									}
									goto LA12;
									LA16: ;
									{
										excl_48474((&(*gch).cycleroots), s_68007);
										{
											if (!((*s_68007).refcount == ((NI) 0))) goto LA21;
											freecycliccell_66415(gch, s_68007);
										}
										LA21: ;
									}
									LA12: ;
								}
								LA10: ;
								j_68045 += ((NI) 1);
								w_68043 = (NI)((NU64)(w_68043) >> (NU64)(((NI) 1)));
							} LA7: ;
						}
						i_68041 += ((NI) 1);
					} LA5: ;
				}
				r_68039 = (*r_68039).next;
			} LA3: ;
		}
	}
	(*gch).stat.cycletablesize = (((*gch).stat.cycletablesize >= tabsize) ? (*gch).stat.cycletablesize : tabsize);
}

N_NIMCALL(void, collectroots_70401)(Gcheap50018* gch) {
	{
		Cell47705* s_70405;
		Cellset47717 HEX3Atmp_70407;
		Pagedesc47713* r_70412;
		s_70405 = 0;
		memset((void*)(&HEX3Atmp_70407), 0, sizeof(HEX3Atmp_70407));
		HEX3Atmp_70407 = (*gch).cycleroots;
		r_70412 = HEX3Atmp_70407.head;
		{
			while (1) {
				NI i_70414;
				if (!!((r_70412 == NIM_NIL))) goto LA3;
				i_70414 = ((NI) 0);
				{
					while (1) {
						NI w_70416;
						NI j_70418;
						if (!(i_70414 <= ((NI) 7))) goto LA5;
						w_70416 = (*r_70412).bits[(i_70414)- 0];
						j_70418 = ((NI) 0);
						{
							while (1) {
								if (!!((w_70416 == ((NI) 0)))) goto LA7;
								{
									if (!!((((NI) ((NI)(w_70416 & ((NI) 1)))) == ((NI) 0)))) goto LA10;
									s_70405 = ((Cell47705*) ((NI)((NI)((NU64)((*r_70412).key) << (NU64)(((NI) 12))) | (NI)((NU64)((NI)((NU64)((NI)((NU64)(i_70414) << (NU64)(((NI) 6)))) + (NU64)(j_70418))) * (NU64)(((NI) 8))))));
									collectwhite_67801(s_70405);
								}
								LA10: ;
								j_70418 += ((NI) 1);
								w_70416 = (NI)((NU64)(w_70416) >> (NU64)(((NI) 1)));
							} LA7: ;
						}
						i_70414 += ((NI) 1);
					} LA5: ;
				}
				r_70412 = (*r_70412).next;
			} LA3: ;
		}
	}
}

N_NIMCALL(void, deinit_47826)(Cellset47717* s) {
	Pagedesc47713* it;
	it = (*s).head;
	{
		while (1) {
			Pagedesc47713* n;
			if (!!((it == NIM_NIL))) goto LA2;
			n = (*it).next;
			dealloc_7448(((void*) (it)));
			it = n;
		} LA2: ;
	}
	(*s).head = NIM_NIL;
	dealloc_7448(((void*) ((*s).data)));
	(*s).data = NIM_NIL;
	(*s).counter = ((NI) 0);
}

N_NIMCALL(void, cellsetreset_56201)(Cellset47717* s) {
	deinit_47826(s);
	init_47818(s);
}

N_NIMCALL(void, collectcycles_70420)(Gcheap50018* gch) {
	{
		while (1) {
			NIM_BOOL LOC3;
			if (!(((NI) 0) < (*gch).zct.len)) goto LA2;
			LOC3 = 0;
			LOC3 = collectzct_70206(gch);
		} LA2: ;
	}
	markroots_68002(gch);
	{
		Cell47705* s_70601;
		Cellset47717 HEX3Atmp_70803;
		Pagedesc47713* r_70808;
		s_70601 = 0;
		memset((void*)(&HEX3Atmp_70803), 0, sizeof(HEX3Atmp_70803));
		HEX3Atmp_70803 = (*gch).cycleroots;
		r_70808 = HEX3Atmp_70803.head;
		{
			while (1) {
				NI i_70810;
				if (!!((r_70808 == NIM_NIL))) goto LA6;
				i_70810 = ((NI) 0);
				{
					while (1) {
						NI w_70812;
						NI j_70814;
						if (!(i_70810 <= ((NI) 7))) goto LA8;
						w_70812 = (*r_70808).bits[(i_70810)- 0];
						j_70814 = ((NI) 0);
						{
							while (1) {
								if (!!((w_70812 == ((NI) 0)))) goto LA10;
								{
									if (!!((((NI) ((NI)(w_70812 & ((NI) 1)))) == ((NI) 0)))) goto LA13;
									s_70601 = ((Cell47705*) ((NI)((NI)((NU64)((*r_70808).key) << (NU64)(((NI) 12))) | (NI)((NU64)((NI)((NU64)((NI)((NU64)(i_70810) << (NU64)(((NI) 6)))) + (NU64)(j_70814))) * (NU64)(((NI) 8))))));
									scan_67601(s_70601);
								}
								LA13: ;
								j_70814 += ((NI) 1);
								w_70812 = (NI)((NU64)(w_70812) >> (NU64)(((NI) 1)));
							} LA10: ;
						}
						i_70810 += ((NI) 1);
					} LA8: ;
				}
				r_70808 = (*r_70808).next;
			} LA6: ;
		}
	}
	collectroots_70401(gch);
	cellsetreset_56201((&(*gch).cycleroots));
}

N_NIMCALL(NI, gettotalmem_8059)(void) {
	NI result;
{	result = 0;
	result = gch_50059.region.currmem;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getfreemem_8057)(void) {
	NI result;
	result = 0;
	result = gch_50059.region.freemem;
	return result;
}

N_NIMCALL(NI, getoccupiedmem_8055)(void) {
	NI result;
	NI LOC1;
	NI LOC2;
{	result = 0;
	LOC1 = 0;
	LOC1 = gettotalmem_8059();
	LOC2 = 0;
	LOC2 = getfreemem_8057();
	result = (NI)(LOC1 - LOC2);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, unmarkstackandregisters_75402)(Gcheap50018* gch) {
	Cell47705** d;
	d = (*gch).decstack.d;
	{
		NI i_75416;
		NI HEX3Atmp_75602;
		NI res_75605;
		i_75416 = 0;
		HEX3Atmp_75602 = 0;
		HEX3Atmp_75602 = (NI)((*gch).decstack.len - ((NI) 1));
		res_75605 = ((NI) 0);
		{
			while (1) {
				if (!(res_75605 <= HEX3Atmp_75602)) goto LA3;
				i_75416 = res_75605;
				decref_53601(d[(i_75416)- 0]);
				res_75605 += ((NI) 1);
			} LA3: ;
		}
	}
	(*gch).decstack.len = ((NI) 0);
}

N_NIMCALL(void, collectctbody_75609)(Gcheap50018* gch) {
	NI LOC1;
	LOC1 = 0;
	LOC1 = stacksize_71801();
	(*gch).stat.maxstacksize = (((*gch).stat.maxstacksize >= LOC1) ? (*gch).stat.maxstacksize : LOC1);
	prepareforinteriorpointerchecking_45088((&(*gch).region));
	markstackandregisters_73037(gch);
	markthreadstacks_71403(gch);
	(*gch).stat.maxstackcells = (((*gch).stat.maxstackcells >= (*gch).decstack.len) ? (*gch).stat.maxstackcells : (*gch).decstack.len);
	(*gch).stat.stackscans += ((NI) 1);
	{
		NIM_BOOL LOC4;
		LOC4 = 0;
		LOC4 = collectzct_70206(gch);
		if (!LOC4) goto LA5;
		{
			NIM_BOOL LOC9;
			NI LOC10;
			NI LOC14;
			LOC9 = 0;
			LOC10 = 0;
			LOC10 = getoccupiedmem_47630((&(*gch).region));
			LOC9 = ((*gch).cyclethreshold <= LOC10);
			if (LOC9) goto LA11;
			LOC9 = NIM_FALSE;
			LA11: ;
			if (!LOC9) goto LA12;
			collectcycles_70420(gch);
			(*gch).stat.cyclecollections += ((NI) 1);
			LOC14 = 0;
			LOC14 = getoccupiedmem_8055();
			(*gch).cyclethreshold = ((((NI) 4194304) >= (NI)(LOC14 * ((NI) 2))) ? ((NI) 4194304) : (NI)(LOC14 * ((NI) 2)));
			(*gch).stat.maxthreshold = (((*gch).stat.maxthreshold >= (*gch).cyclethreshold) ? (*gch).stat.maxthreshold : (*gch).cyclethreshold);
		}
		LA12: ;
	}
	LA5: ;
	unmarkstackandregisters_75402(gch);
}

N_NIMCALL(void, collectct_52007)(Gcheap50018* gch) {
	NI stackmarkcosts;
	NI LOC1;
	LOC1 = 0;
	LOC1 = stacksize_71801();
	stackmarkcosts = (((NI)(LOC1 / ((NI) 128)) >= ((NI) 500)) ? (NI)(LOC1 / ((NI) 128)) : ((NI) 500));
	{
		NIM_BOOL LOC4;
		NIM_BOOL LOC5;
		NIM_BOOL LOC6;
		NIM_BOOL LOC8;
		NI LOC10;
		LOC4 = 0;
		LOC5 = 0;
		LOC6 = 0;
		LOC6 = (stackmarkcosts <= (*gch).zct.len);
		if (LOC6) goto LA7;
		LOC8 = 0;
		LOC8 = NIM_TRUE;
		if (!(LOC8)) goto LA9;
		LOC10 = 0;
		LOC10 = getoccupiedmem_47630((&(*gch).region));
		LOC8 = ((*gch).cyclethreshold <= LOC10);
		LA9: ;
		LOC6 = LOC8;
		LA7: ;
		LOC5 = LOC6;
		if (LOC5) goto LA11;
		LOC5 = NIM_FALSE;
		LA11: ;
		LOC4 = LOC5;
		if (!(LOC4)) goto LA12;
		LOC4 = ((*gch).recgclock == ((NI) 0));
		LA12: ;
		if (!LOC4) goto LA13;
		collectctbody_75609(gch);
	}
	LA13: ;
}

static N_INLINE(void, addnewobjtozct_57274)(Cell47705* res, Gcheap50018* gch) {
	NI L;
	Cell47705** d;
{	L = (*gch).zct.len;
	d = (*gch).zct.d;
	{
		Cell47705* c;
		if (!(((NI) 8) < L)) goto LA3;
		c = 0;
		c = d[((NI)(L - ((NI) 1)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA7;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 1)))- 0] = res;
			goto BeforeRet;
		}
		LA7: ;
		c = d[((NI)(L - ((NI) 2)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA11;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 2)))- 0] = res;
			goto BeforeRet;
		}
		LA11: ;
		c = d[((NI)(L - ((NI) 3)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA15;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 3)))- 0] = res;
			goto BeforeRet;
		}
		LA15: ;
		c = d[((NI)(L - ((NI) 4)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA19;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 4)))- 0] = res;
			goto BeforeRet;
		}
		LA19: ;
		c = d[((NI)(L - ((NI) 5)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA23;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 5)))- 0] = res;
			goto BeforeRet;
		}
		LA23: ;
		c = d[((NI)(L - ((NI) 6)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA27;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 6)))- 0] = res;
			goto BeforeRet;
		}
		LA27: ;
		c = d[((NI)(L - ((NI) 7)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA31;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 7)))- 0] = res;
			goto BeforeRet;
		}
		LA31: ;
		c = d[((NI)(L - ((NI) 8)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA35;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 8)))- 0] = res;
			goto BeforeRet;
		}
		LA35: ;
		add_47783((&(*gch).zct), res);
	}
	goto LA1;
	LA3: ;
	{
		d[(L)- 0] = res;
		(*gch).zct.len += ((NI) 1);
	}
	LA1: ;
	}BeforeRet: ;
}

N_NIMCALL(void*, rawnewobj_57801)(TNimType* typ, NI size, Gcheap50018* gch) {
	void* result;
	Cell47705* res;
	void* LOC1;
	result = 0;
	collectct_52007(gch);
	LOC1 = 0;
	LOC1 = rawalloc_37068((&(*gch).region), (NI)(size + ((NI)sizeof(Cell47705))));
	res = ((Cell47705*) (LOC1));
	(*res).typ = typ;
	(*res).refcount = ((NI) 4);
	addnewobjtozct_57274(res, gch);
	result = celltousr_51622(res);
	return result;
}

N_NIMCALL(void*, newObjNoInit)(TNimType* typ, NI size) {
	void* result;
	result = 0;
	result = rawnewobj_57801(typ, size, (&gch_50059));
	return result;
}

N_NIMCALL(NimStringDesc*, rawNewStringNoInit)(NI space) {
	NimStringDesc* result;
	NI s;
	void* LOC5;
	result = 0;
	s = space;
	{
		if (!(s < ((NI) 7))) goto LA3;
		s = ((NI) 7);
	}
	LA3: ;
	LOC5 = 0;
	LOC5 = newObjNoInit((&strdesc_12203), (NI)((NI)(((NI)sizeof(TGenericSeq)) + s) + ((NI) 1)));
	result = ((NimStringDesc*) (LOC5));
	(*result).Sup.reserved = s;
	return result;
}

N_NIMCALL(NimStringDesc*, toNimStr)(NCSTRING str, NI len) {
	NimStringDesc* result;
	result = 0;
	result = rawNewStringNoInit(len);
	(*result).Sup.len = len;
	memcpy(((NCSTRING) ((*result).data)), str, (NI)(len + ((NI) 1)));
	return result;
}

N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str) {
	NimStringDesc* result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = strlen(str);
	result = toNimStr(str, LOC1);
	return result;
}

N_NIMCALL(void, write_15701)(FILE* f, NCSTRING c) {
	fputs(c, f);
}

N_NIMCALL(void, writetostderr_19601)(NCSTRING msg) {
	write_15701(stderr, msg);
}

N_NIMCALL(void, showerrormessage_19606)(NCSTRING data) {
	{
		NimStringDesc* LOC5;
		if (!!((errormessagewriter_19404 == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = cstrToNimstr(data);
		errormessagewriter_19404(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		writetostderr_19601(data);
	}
	LA1: ;
}

N_NOCONV(void, signalHandler)(int sig) {
	NCSTRING msg;
	msg = 0;
	{
		if (!(sig == SIGINT)) goto LA3;
		msg = "SIGINT: Interrupted by Ctrl-C.\012";
	}
	goto LA1;
	LA3: ;
	{
		if (!(sig == SIGSEGV)) goto LA6;
		msg = "SIGSEGV: Illegal storage access. (Attempt to read from nil?)\012";
	}
	goto LA1;
	LA6: ;
	{
		if (!(sig == SIGABRT)) goto LA9;
		msg = "SIGABRT: Abnormal termination.\012";
	}
	goto LA1;
	LA9: ;
	{
		if (!(sig == SIGFPE)) goto LA12;
		msg = "SIGFPE: Arithmetic error.\012";
	}
	goto LA1;
	LA12: ;
	{
		if (!(sig == SIGILL)) goto LA15;
		msg = "SIGILL: Illegal operation.\012";
	}
	goto LA1;
	LA15: ;
	{
		if (!(sig == SIGBUS)) goto LA18;
		msg = "SIGBUS: Illegal storage access. (Attempt to read from nil?)\012";
	}
	goto LA1;
	LA18: ;
	{
		{
			{
				if (!(sig == SIGPIPE)) goto LA24;
				msg = "SIGPIPE: Pipe closed.\012";
				goto LA21;
			}
			LA24: ;
			msg = "unknown signal\012";
		} LA21: ;
	}
	LA1: ;
	showerrormessage_19606(msg);
	exit(((NI) 1));
}

N_NIMCALL(void, registersignalhandler_23202)(void) {
	signal(SIGINT, signalHandler);
	signal(SIGSEGV, signalHandler);
	signal(SIGABRT, signalHandler);
	signal(SIGFPE, signalHandler);
	signal(SIGILL, signalHandler);
	signal(SIGBUS, signalHandler);
	signal(SIGPIPE, signalHandler);
}

N_NIMCALL(NI, getRefcount)(void* p) {
	NI result;
	Cell47705* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = usrtocell_51640(p);
	result = (NI)((NU64)((*LOC1).refcount) >> (NU64)(((NI) 3)));
	return result;
}
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void) {
	TNimType LOC1;
	nimvm_5751 = NIM_FALSE;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.size = ((NI) 8);
	LOC1.kind = ((NU8) 28);
	LOC1.flags = 2;
	strdesc_12203 = LOC1;
	initallocator_11601();
	initStackBottom();
	initgc_11401();
	registersignalhandler_23202();
}

NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void) {
}

